### ISSUE TITLE
What is the deployment plan for Zebra-Lite

### ISSUE THREAD

**Issue by geoffreymuchai** [onaio/zebra-lite#19]

**Comment by pld** [comment]
The plan is to provide comprehensive documentation so others can run zebra-lite, we won't be running it ourselves until we begin using it in dashboards.

For dashboards, that are based on zebra-lite, perhaps we can have a generic dashboard deployment playbook that we add inventories to for each specific dashboard.

Also, if we move completely to CLJS, front-end only, deploy should be hosting assets (webpage, images, JS) something that can happen for free on github and other places.

**Comment by geoffreymuchai** [comment]
Thanks for the clarification
